server:
  port: 8000
app:
  urlCodeLength: 8
  maxAttempts: 10
  publicDomain: "http://localhost:8000"
database:
  url: postgres://user:password@db.docker.localhost:5432/url_shortener
  maxConnections: 10
  minConnection: 2
  maxConnectionLifetime: 60 # seconds
  maxConnectionIdleTime: 1 # minutes
redist:
  host: redis.db.localhost:6379
  username: user
  password: password