database:
  url: postgres://user:password@db.docker.localhost:5432/url_shortener
  maxConnections: 10
  minConnection: 2
  maxConnectionLifetime: 60 # seconds
  maxConnectionIdleTime: 1 # minutes
server:
  port: 8000
app:
  urlCodeLength: 8
  maxAttempts: 10