name: url-shortener
services:
  traefik:
    image: "traefik:v3.4"
    container_name: "url-shortener-traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - url-shortener
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
  db:
    image: "postgres:16-alpine"
    container_name: "url-shortener-db"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - url-shortener
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`db.docker.localhost`)"
      - "traefik.http.routers.db.entrypoints=db"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine3.22"
    container_name: "url-shortener-redis"
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - redis:/data
    env_file:
      - ./.env
    networks:
      - url-shortener
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`redis.docker.localhost`)"
      - "traefik.http.routers.db.entrypoints=redis"
    ports:
      - 6379:6379
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - ./.env
    ports:
      - 22181:2181
    networks:
      - url-shortener
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`zookeeper.docker.localhost`)"
      - "traefik.http.routers.db.entrypoints=zookeeper"
  kafka:
    image: confluentinc/cp-server:7.2.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    env_file:
      - ./.env
    networks:
      - url-shortener
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`kafka.docker.localhost`)"
      - "traefik.http.routers.db.entrypoints=kafka"
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    env_file:
      - ./.env
    networks:
      - url-shortener
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`kafka-ui.docker.localhost`)"
      - "traefik.http.routers.db.entrypoints=kafka-ui"
volumes:
  db:
  redis:
networks:
  url-shortener:
